In [12]:
# importing libraries used is 1st task

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

# using dataset

In [13]:
dataset = pd.read_csv('C:/Users/Asus/Desktop/dataset_infobyte/Iris.csv')
dataset.head(4)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa

In [14]:
# analyze of data
dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

# species of iris flower

In [15]:
dataset['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

# Model training

dividing data:

In [16]:
from ctypes import sizeof
from sklearn.model_selection import train_test_split
X = dataset.drop(columns=['Species'])
Y = dataset['Species']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state = 42)
print('Size of training dataset : ', len(X_train))
print('Size of testing dataset : ', len(X_test))
     

Size of training dataset :  105
Size of testing dataset :  45


Logistic Regression:

In [17]:
from sklearn.linear_model import LogisticRegression

LR_model = LogisticRegression(max_iter=1000)    #iteration limit has been reached so that we using this fun to increase the limit
LR_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

# Model Evaluation

In [18]:
expected = np.array(y_test)
predicted = LR_model.predict(X_test)


In [19]:
print("Accuracy of our Logistic Regression Model :", LR_model.score(X_test, y_test)*100)

Accuracy of our Logistic Regression Model : 100.0


In [20]:
from sklearn import metrics
print('-confusion Matrix : ')
print(metrics.confusion_matrix(expected, predicted))

-confusion Matrix : 
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [21]:
print(metrics.classification_report(expected, predicted))     

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



In [22]:
for i in range(len(predicted)):
  print('Predicted : ' + predicted[i] + '   ||  Actual is : ' + expected[i])

Predicted : Iris-versicolor   ||  Actual is : Iris-versicolor
Predicted : Iris-setosa   ||  Actual is : Iris-setosa
Predicted : Iris-virginica   ||  Actual is : Iris-virginica
Predicted : Iris-versicolor   ||  Actual is : Iris-versicolor
Predicted : Iris-versicolor   ||  Actual is : Iris-versicolor
Predicted : Iris-setosa   ||  Actual is : Iris-setosa
Predicted : Iris-versicolor   ||  Actual is : Iris-versicolor
Predicted : Iris-virginica   ||  Actual is : Iris-virginica
Predicted : Iris-versicolor   ||  Actual is : Iris-versicolor
Predicted : Iris-versicolor   ||  Actual is : Iris-versicolor
Predicted : Iris-virginica   ||  Actual is : Iris-virginica
Predicted : Iris-setosa   ||  Actual is : Iris-setosa
Predicted : Iris-setosa   ||  Actual is : Iris-setosa
Predicted : Iris-setosa   ||  Actual is : Iris-setosa
Predicted : Iris-setosa   ||  Actual is : Iris-setosa
Predicted : Iris-versicolor   ||  Actual is : Iris-versicolor
Predicted : Iris-virginica   ||  Actual is : Iris-virginica
Pr